Bubble Sort - Ruby's 1st Project
camfilho/ruby-bubble-sort pull request #1
Opened 2019-11-01 20:00 UTC by camfilho

2019-11-02 17:54 UTC, whiz25 commented on bubblesort.rb
> +      # swaping
remove tbis comment

2019-11-02 17:56 UTC, whiz25 commented on bubblesort.rb
> +  arr = _arr2.dup
is it ```_arr2``` or ```arr2```?. Undefined error is being thrown on that line.

2019-11-02 18:00 UTC, whiz25 requested changes
## Amazing job 👍 
Your code is clean. That's good. However, we can not merge this PR yet.
- [ ] check my comments and implement those changes
- [ ] make your README more descriptive. Add a section for ```Getting started, stacks used, etc```.

#### Make those changes and re-submit for another review.

### Martin Afani

2019-11-11 12:27 UTC, Torres-ssf approved these changes
### Project Approved :+1: :tada: 

I'm approving this project, nice job on it
Go on and merge to master.

Good luck on the next ones.
Happy coding :computer:

2019-11-11 14:43 UTC, merged